### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by PolarPeak** [MaxBresil/LStegB#1]
[+] Starting basic process...
ProcessingTraceback (most recent call last):
  File "LStegB.py", line 421, in <module>
    main()
  File "LStegB.py", line 395, in main
    basic_bf(im, width, height, bits_quantity, channels, steps)
  File "LStegB.py", line 159, in basic_bf
    basic(im, width, height, bit, channel, height_step, width_step, False, False)
  File "LStegB.py", line 129, in basic
    r, g, b = pixels[width_pixel, height_pixel]
ValueError: too many values to unpack (expected 3)
![image](https://user-images.githubusercontent.com/44831329/100719572-c467ae80-33f7-11eb-8b76-4ab2021a5978.png)

**Comment by x1mus** [comment]
Working on it, can you send me the image you're trying to decode ?
It should be related to the fact that your image is RGB with an Alpha channel. Known issue, working on it ;)

**Comment by PolarPeak** [comment]
> 正在处理它，您可以将要解码的图像发送给我吗？
> 这应该与以下事实有关：您的图像是带有Alpha通道的RGB。已知问题，正在研究中；）

![flag](https://user-images.githubusercontent.com/44831329/100720358-d433c280-33f8-11eb-97cb-30b61ad44fbe.png)

**Comment by PolarPeak** [comment]
如果那个图像不可用，您可以留下您的邮箱，我通过邮箱发给您

**Comment by x1mus** [comment]
Hey !
I'm currently trying to solve the issue (I know where it's at but I'd like to know the solution of this challenge).
Can you point me to the CTF name where you found this challenge ? :)

**Comment by PolarPeak** [comment]
Just the LSB with the secret key，the secret key is 123456

**Comment by x1mus** [comment]
Oh, there was a key to find it ?
Do you have a link to a complete write-up ? ^^

**Comment by x1mus** [comment]
Fixed in commit [#10](https://github.com/x1mus/LStegB/commit/266ab377651801a882741b5aa080adabb142f44c)
